/*
 * pio_backend_rp1.c - Real PIOLib backend for RP1 hardware
 *
 * Wraps PIOLib API calls to control the RP1 PIO subsystem on
 * Raspberry Pi 5. Requires /dev/pio0 and PIOLib headers.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef HAVE_PIOLIB

#include "pio_backend.h"
#include "rp1_jtag.h"   /* for RP1_JTAG_ERR_* error codes */
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/*
 * PIOLib headers -- installed at /usr/include/piolib/
 * The PIOLib API mirrors the Pico SDK API, providing userspace access
 * to the RP1 PIO hardware via /dev/pio0.
 */
#include <hardware/pio.h>

/*
 * PIO program headers (generated by pioasm).
 * With PIOLib available (!PICO_NO_HARDWARE), these provide:
 *   - pio_program struct (for pio_add_program)
 *   - get_default_config helper (sets wrap, sideset from .pio metadata)
 */
#include "pio/generated/jtag_shift.pio.h"
#include "pio/generated/jtag_shift_fast.pio.h"
#include "pio/generated/jtag_loopback.pio.h"
#include "pio/generated/jtag_target.pio.h"

typedef struct {
    pio_backend_t base;
    PIO pio;
    int sm;
    uint offset;
    bool initialized;
    pio_program_id_t current_program;
    const pio_program_t *current_pio_prog;
} rp1_backend_t;

/* Map program ID to pioasm-generated pio_program_t struct */
static const pio_program_t *get_pio_program(pio_program_id_t id)
{
    switch (id) {
    case PIO_PROG_JTAG_SHIFT:      return &jtag_shift_program;
    case PIO_PROG_JTAG_SHIFT_FAST: return &jtag_shift_fast_program;
    case PIO_PROG_JTAG_LOOPBACK:   return &jtag_loopback_program;
    case PIO_PROG_JTAG_TARGET:     return &jtag_target_program;
    default:                        return NULL;
    }
}

/* Get default SM config from pioasm-generated helper (sets wrap, sideset) */
static pio_sm_config get_program_config(pio_program_id_t id, uint offset)
{
    switch (id) {
    case PIO_PROG_JTAG_SHIFT:      return jtag_shift_program_get_default_config(offset);
    case PIO_PROG_JTAG_SHIFT_FAST: return jtag_shift_fast_program_get_default_config(offset);
    case PIO_PROG_JTAG_LOOPBACK:   return jtag_loopback_program_get_default_config(offset);
    case PIO_PROG_JTAG_TARGET:     return jtag_target_program_get_default_config(offset);
    default: {
        /* Fallback: should never happen */
        return pio_get_default_sm_config();
    }
    }
}

static int rp1_init(pio_backend_t *be, pio_program_id_t prog,
                    const pio_sm_pins_t *pins)
{
    rp1_backend_t *r = (rp1_backend_t *)be;

    /* Global PIO subsystem init */
    if (pio_init() < 0) {
        fprintf(stderr, "rp1_jtag: pio_init() failed\n");
        return RP1_JTAG_ERR_NODEV;
    }

    /* Open PIO0 instance */
    r->pio = pio_open(0);
    if (PIO_IS_ERR(r->pio)) {
        fprintf(stderr, "rp1_jtag: failed to open PIO0 "
                "(is /dev/pio0 available?)\n");
        return RP1_JTAG_ERR_NODEV;
    }

    /* Claim a state machine */
    r->sm = pio_claim_unused_sm(r->pio, false);
    if (r->sm < 0) {
        fprintf(stderr, "rp1_jtag: no free state machines\n");
        pio_close(r->pio);
        return RP1_JTAG_ERR_BUSY;
    }

    /* Load PIO program into instruction memory */
    const pio_program_t *pio_prog = get_pio_program(prog);
    if (!pio_prog) {
        pio_sm_unclaim(r->pio, r->sm);
        pio_close(r->pio);
        return RP1_JTAG_ERR_PARAM;
    }

    r->offset = pio_add_program(r->pio, pio_prog);
    if (r->offset == PIO_ORIGIN_INVALID) {
        fprintf(stderr, "rp1_jtag: no program space in PIO instruction memory\n");
        pio_sm_unclaim(r->pio, r->sm);
        pio_close(r->pio);
        return RP1_JTAG_ERR_IO;
    }

    r->current_program = prog;
    r->current_pio_prog = pio_prog;
    r->initialized = true;

    /* Configure SM */
    if (pins) {
        /*
         * Select this PIO instance so sm_config_set_* functions
         * (which use pio_get_current() internally) work correctly.
         */
        pio_select(r->pio);

        /* Get default config from pioasm (sets wrap + sideset from .pio) */
        pio_sm_config c = get_program_config(prog, r->offset);

        /* TCK: sideset pin (toggled by every PIO instruction's side-set) */
        if (pins->sideset_base >= 0) {
            sm_config_set_sideset_pins(&c, pins->sideset_base);
            pio_gpio_init(r->pio, pins->sideset_base);
            pio_sm_set_consecutive_pindirs(r->pio, r->sm,
                                           pins->sideset_base, 1, true);
        }

        /* TDI: OUT pin (data shifted from TX FIFO) */
        if (pins->out_base >= 0) {
            sm_config_set_out_pins(&c, pins->out_base, 1);
            pio_gpio_init(r->pio, pins->out_base);
            pio_sm_set_consecutive_pindirs(r->pio, r->sm,
                                           pins->out_base, 1, true);
        }

        /* TDO: IN pin (data shifted to RX FIFO) */
        if (pins->in_base >= 0) {
            sm_config_set_in_pins(&c, pins->in_base);
            pio_gpio_init(r->pio, pins->in_base);
            /* IN pin is input -- default direction is input, no change needed */
        }

        /* TMS: host-controlled GPIO output (not a PIO pin) */
        if (pins->tms_base >= 0) {
            pio_gpio_init(r->pio, pins->tms_base);
            pio_sm_set_consecutive_pindirs(r->pio, r->sm,
                                           pins->tms_base, 1, true);
        }

        if (pins->clk_div > 0)
            sm_config_set_clkdiv(&c, pins->clk_div);

        /*
         * Shift config: LSB-first (JTAG spec), autopull/autopush at 32.
         *
         * Autopull: The jtag_shift program uses explicit pull for the
         * count word, then autopull kicks in for subsequent TDI data
         * words after out x,32 depletes the OSR.
         *
         * Autopush: Every 32 `in` instructions, the ISR is automatically
         * pushed to RX FIFO and reset. Without autopush, transfers >32
         * bits would lose data (ISR overflows) and deadlock (host waits
         * for RX words that never arrive). The explicit `push` at the
         * end of jtag_shift/jtag_loopback flushes the final partial word.
         */
        sm_config_set_out_shift(&c, true, true, 32);  /* LSB-first, autopull */
        sm_config_set_in_shift(&c, true, true, 32);   /* LSB-first, autopush */

        /* Initialize SM with config, starting at program offset */
        pio_sm_init(r->pio, r->sm, r->offset, &c);
    }

    return 0;
}

static void rp1_close(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    if (r->initialized) {
        pio_sm_set_enabled(r->pio, r->sm, false);
        if (r->current_pio_prog)
            pio_remove_program(r->pio, r->current_pio_prog, r->offset);
        pio_sm_unclaim(r->pio, r->sm);
        pio_close(r->pio);
        r->initialized = false;
    }
}

static int rp1_set_clk_div(pio_backend_t *be, float div)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_set_clkdiv(r->pio, r->sm, div);
    return 0;
}

static int rp1_gpio_set(pio_backend_t *be, int pin, bool value)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    /*
     * Set a GPIO pin value for TMS/SRST/TRST control.
     * The pin must already be initialized as a PIO GPIO output (done in init).
     */
    uint32_t mask = 1u << pin;
    uint32_t val = value ? mask : 0;
    pio_sm_set_pins_with_mask(r->pio, r->sm, val, mask);
    return 0;
}

static int rp1_sm_put(pio_backend_t *be, uint32_t word)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_put_blocking(r->pio, r->sm, word);
    return 0;
}

static int rp1_sm_get(pio_backend_t *be, uint32_t *word)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    *word = pio_sm_get_blocking(r->pio, r->sm);
    return 0;
}

static bool rp1_tx_fifo_has_space(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    return !pio_sm_is_tx_fifo_full(r->pio, r->sm);
}

static bool rp1_rx_fifo_has_data(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    return !pio_sm_is_rx_fifo_empty(r->pio, r->sm);
}

static int rp1_sm_set_enabled(pio_backend_t *be, bool enabled)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_set_enabled(r->pio, r->sm, enabled);
    return 0;
}

static int rp1_load_program(pio_backend_t *be, pio_program_id_t prog)
{
    rp1_backend_t *r = (rp1_backend_t *)be;

    /* Remove old program first */
    if (r->current_pio_prog)
        pio_remove_program(r->pio, r->current_pio_prog, r->offset);

    /* Load new program */
    const pio_program_t *pio_prog = get_pio_program(prog);
    if (!pio_prog)
        return RP1_JTAG_ERR_PARAM;

    r->offset = pio_add_program(r->pio, pio_prog);
    if (r->offset == PIO_ORIGIN_INVALID)
        return RP1_JTAG_ERR_IO;

    r->current_program = prog;
    r->current_pio_prog = pio_prog;
    return 0;
}

static const pio_backend_ops_t rp1_ops = {
    .init             = rp1_init,
    .close            = rp1_close,
    .set_clk_div      = rp1_set_clk_div,
    .gpio_set         = rp1_gpio_set,
    .sm_put           = rp1_sm_put,
    .sm_get           = rp1_sm_get,
    .tx_fifo_has_space = rp1_tx_fifo_has_space,
    .rx_fifo_has_data  = rp1_rx_fifo_has_data,
    .sm_set_enabled   = rp1_sm_set_enabled,
    .load_program     = rp1_load_program,
};

pio_backend_t *pio_backend_rp1_create(void)
{
    rp1_backend_t *r = calloc(1, sizeof(rp1_backend_t));
    if (!r)
        return NULL;
    r->base.ops = &rp1_ops;
    return &r->base;
}

#else /* !HAVE_PIOLIB */

#include "pio_backend.h"
#include <stdio.h>

pio_backend_t *pio_backend_rp1_create(void)
{
    fprintf(stderr, "rp1_jtag: compiled without PIOLib support\n");
    return NULL;
}

#endif /* HAVE_PIOLIB */
