/*
 * pio_backend_rp1.c - Real PIOLib backend for RP1 hardware
 *
 * Wraps PIOLib API calls to control the RP1 PIO subsystem on
 * Raspberry Pi 5. Requires /dev/pio0 and PIOLib headers.
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#ifdef HAVE_PIOLIB

#include "pio_backend.h"
#include <stdlib.h>
#include <string.h>
#include <stdio.h>

/* PIOLib headers */
#include <pio_platform.h>
#include <hardware/pio.h>

/* PIO program headers (generated by pioasm) */
#define PICO_NO_HARDWARE 1
#include "pio/generated/jtag_shift.pio.h"
#include "pio/generated/jtag_shift_fast.pio.h"
#include "pio/generated/jtag_loopback.pio.h"
#include "pio/generated/jtag_target.pio.h"
#undef PICO_NO_HARDWARE

typedef struct {
    pio_backend_t base;
    PIO pio;
    int sm;
    uint offset;
    bool initialized;
    pio_program_id_t current_program;
} rp1_backend_t;

static const uint16_t *program_instructions(pio_program_id_t id, int *len)
{
    switch (id) {
    case PIO_PROG_JTAG_SHIFT:
        *len = sizeof(jtag_shift_program_instructions) / sizeof(uint16_t);
        return jtag_shift_program_instructions;
    case PIO_PROG_JTAG_SHIFT_FAST:
        *len = sizeof(jtag_shift_fast_program_instructions) / sizeof(uint16_t);
        return jtag_shift_fast_program_instructions;
    case PIO_PROG_JTAG_LOOPBACK:
        *len = sizeof(jtag_loopback_program_instructions) / sizeof(uint16_t);
        return jtag_loopback_program_instructions;
    case PIO_PROG_JTAG_TARGET:
        *len = sizeof(jtag_target_program_instructions) / sizeof(uint16_t);
        return jtag_target_program_instructions;
    default:
        *len = 0;
        return NULL;
    }
}

static int rp1_init(pio_backend_t *be, pio_program_id_t prog,
                    const pio_sm_pins_t *pins)
{
    rp1_backend_t *r = (rp1_backend_t *)be;

    /* Open PIO instance */
    r->pio = pio0;
    if (pio_init(r->pio) < 0) {
        fprintf(stderr, "rp1_jtag: failed to init PIO (is /dev/pio0 available?)\n");
        return RP1_JTAG_ERR_NODEV;
    }

    /* Claim a state machine */
    r->sm = pio_claim_unused_sm(r->pio, true);
    if (r->sm < 0) {
        fprintf(stderr, "rp1_jtag: no free state machines\n");
        return RP1_JTAG_ERR_BUSY;
    }

    /* Load program */
    int prog_len;
    const uint16_t *prog_insn = program_instructions(prog, &prog_len);
    if (!prog_insn)
        return RP1_JTAG_ERR_PARAM;

    /* TODO: Use pio_add_program() to load instructions into PIO memory.
     * PIOLib API for RP1 may differ from RP2040 SDK. This needs to be
     * adapted once we test on real hardware. */
    r->current_program = prog;
    r->initialized = true;

    /* Configure pins */
    if (pins) {
        pio_sm_config c = pio_get_default_sm_config();

        if (pins->sideset_base >= 0) {
            sm_config_set_sideset_pins(&c, pins->sideset_base);
            sm_config_set_sideset(&c, 1, false, false);
            pio_gpio_init(r->pio, pins->sideset_base);
            pio_sm_set_consecutive_pindirs(r->pio, r->sm,
                                           pins->sideset_base, 1, true);
        }
        if (pins->out_base >= 0) {
            sm_config_set_out_pins(&c, pins->out_base, 1);
            pio_gpio_init(r->pio, pins->out_base);
            pio_sm_set_consecutive_pindirs(r->pio, r->sm,
                                           pins->out_base, 1, true);
        }
        if (pins->in_base >= 0) {
            sm_config_set_in_pins(&c, pins->in_base);
            /* IN pin is input, no pindirs change needed */
        }

        if (pins->clk_div > 0)
            sm_config_set_clkdiv(&c, pins->clk_div);

        /* Configure shift: LSB-first, autopush at 32 for loopback */
        sm_config_set_out_shift(&c, true, false, 32); /* LSB-first, no autopull */
        sm_config_set_in_shift(&c, true, false, 32);  /* LSB-first, no autopush */

        pio_sm_init(r->pio, r->sm, r->offset, &c);
    }

    return 0;
}

static void rp1_close(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    if (r->initialized) {
        pio_sm_set_enabled(r->pio, r->sm, false);
        pio_sm_unclaim(r->pio, r->sm);
        r->initialized = false;
    }
}

static int rp1_set_clk_div(pio_backend_t *be, float div)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_set_clkdiv(r->pio, r->sm, div);
    return 0;
}

static int rp1_gpio_set(pio_backend_t *be, int pin, bool value)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_gpio_init(r->pio, pin);
    gpio_put(pin, value);
    return 0;
}

static int rp1_sm_put(pio_backend_t *be, uint32_t word)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_put_blocking(r->pio, r->sm, word);
    return 0;
}

static int rp1_sm_get(pio_backend_t *be, uint32_t *word)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    *word = pio_sm_get_blocking(r->pio, r->sm);
    return 0;
}

static bool rp1_tx_fifo_has_space(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    return !pio_sm_is_tx_fifo_full(r->pio, r->sm);
}

static bool rp1_rx_fifo_has_data(pio_backend_t *be)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    return !pio_sm_is_rx_fifo_empty(r->pio, r->sm);
}

static int rp1_sm_set_enabled(pio_backend_t *be, bool enabled)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    pio_sm_set_enabled(r->pio, r->sm, enabled);
    return 0;
}

static int rp1_load_program(pio_backend_t *be, pio_program_id_t prog)
{
    rp1_backend_t *r = (rp1_backend_t *)be;
    /* TODO: Remove old program, load new one */
    r->current_program = prog;
    return 0;
}

static const pio_backend_ops_t rp1_ops = {
    .init             = rp1_init,
    .close            = rp1_close,
    .set_clk_div      = rp1_set_clk_div,
    .gpio_set         = rp1_gpio_set,
    .sm_put           = rp1_sm_put,
    .sm_get           = rp1_sm_get,
    .tx_fifo_has_space = rp1_tx_fifo_has_space,
    .rx_fifo_has_data  = rp1_rx_fifo_has_data,
    .sm_set_enabled   = rp1_sm_set_enabled,
    .load_program     = rp1_load_program,
};

pio_backend_t *pio_backend_rp1_create(void)
{
    rp1_backend_t *r = calloc(1, sizeof(rp1_backend_t));
    if (!r)
        return NULL;
    r->base.ops = &rp1_ops;
    return &r->base;
}

#else /* !HAVE_PIOLIB */

#include "pio_backend.h"
#include <stdio.h>

pio_backend_t *pio_backend_rp1_create(void)
{
    fprintf(stderr, "rp1_jtag: compiled without PIOLib support\n");
    return NULL;
}

#endif /* HAVE_PIOLIB */
